<?php

return [
    'date_format'         => 'Y-m-d',
    'time_format'         => 'H:i:s',
    'primary_language'    => 'en',
    'available_languages' => [
        'en'      => 'English',
        'lt'      => 'Lithuanian',
        'de'      => 'German',
        'ru'      => 'Russian',
        'fr'      => 'French',
        'es'      => 'Spanish',
        'pt-br'   => 'Brazilian Portuguese',
        'id'      => 'Indonesian',
        'nl'      => 'Dutch',
        'tr'      => 'Turkish',
        'bg'      => 'Bulgarian',
        'hu'      => 'Hungarian',
        'ua'      => 'Ukrainian',
        'ca'      => 'Catalan',
        'it'      => 'Italian',
        'ar'      => 'Arabic',
        'pl'      => 'Polish',
        'se'      => 'Swedish',
        'ro'      => 'Romanian',
        'pt'      => 'Portuguese',
        'vi'      => 'Vietnamese',
        'am'      => 'Armenian',
        'sr'      => 'Serbian (Latin)',
        'hr'      => 'Croatian',
        'cs'      => 'Czech',
        'bn'      => 'Bengali',
        'ms'      => 'Malay',
        'dk'      => 'Danish',
        'zh'      => 'Traditional Chinese',
        'sk'      => 'Slovak',
        'cnr'     => 'Montenegrin',
        'af'      => 'Afrikaans',
        'zh-Hans' => 'Chinese',
        'th'      => 'Thai',
        'no'      => 'Norwegian-Bokmal',
        'mn'      => 'Mongolian',
        'el'      => 'Greek',
        'fa'      => 'Persian',
        'gu'      => 'Gujarati',
        'hi'      => 'Hindi',
        'ee'      => 'Estonian',
        'al'      => 'Albanian',
        'by'      => 'Belarusian',
        'sl'      => 'Slovenian',
        'lv'      => 'Latvian',
        'uz'      => 'Uzbek',
        'ps'      => 'Pashto',
        'fi'      => 'Finnish',
        'he'      => 'Hebrew',
        'ta'      => 'Tamil',
        'si'      => 'Sinhala',
    ],

];
